version: '2'
services:
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    ports:
      - 8082:80
    volumes:
      - /var/www/html
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secure-password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: {}
  wordpress_data: {}
